export enum ProbabilityFunctionType {
  GOTO = "GOTO",
  PAY = "PAY",
  COLLECT = "COLLECT",
  GIVE = "GIVE",
  PAY_FOR_HOTELS = "PAY_FOR_HOTELS",
  PAY_FOR_HOUSES = "PAY_FOR_HOUSES",
  POTENTIALLY_GET = "POTENTIALLY_GET",
  EITHER = "EITHER",
  COLLECT_FROM_EACH_PLAYER = "COLLECT_FROM_EACH_PLAYER",
  DONT_COLLECT = "DONT_COLLECT",
}
